default: &default
  adapter: postgresql
  encoding: unicode
  hostname: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: myapp
  password: password1

development:
  <<: *default
  database: treasure_hunt_development

test:
  <<: *default
  database: treasure_hunt_test

production:
  <<: *default
  database: treasure_hunt_production
  username: treasure_hunt
  password: <%= ENV['TREASURE_HUNT_DATABASE_PASSWORD'] %>
